### ISSUE TITLE
Array of strings as label for data

### ISSUE THREAD

**Issue by claudiocantieni** [Jonathan-Gander/LineChartView#13]
Would it be possible to configure an array of strings which is displayed in place of the data value in the same way as with the dataLabels.

**Comment by Jonathan-Gander** [comment]
How? I need an array of values (numeric) to display them on the chart. Strings can't be calculated on chart. You can convert your strings into numeric values, no?

You can also add prefix or suffix to your values to display, for example, '45 mph'.

**Comment by claudiocantieni** [comment]
My idea would be that the values are still in the background and responsible for the line but visible are only the strings.
________________________________
Von: Jonathan Gander ***@***.***>
Gesendet: Sonntag, Mai 29, 2022 4:06 PM
An: Jonathan-Gander/LineChartView ***@***.***>
Cc: Claudio Cantieni ***@***.***>; Author ***@***.***>
Betreff: Re: [Jonathan-Gander/LineChartView] Array of strings as label for data (Issue #13)


How? I need an array of values (numeric) to display them on the chart. Strings can't be calculated on chart. You can concert your strings into numeric values, no?

**Comment by Jonathan-Gander** [comment]
Aaah! OK, I got it!

I will have a look.

**Comment by claudiocantieni** [comment]
Thank you!
________________________________
Von: Jonathan Gander ***@***.***>
Gesendet: Sunday, May 29, 2022 5:03:32 PM
An: Jonathan-Gander/LineChartView ***@***.***>
Cc: Claudio Cantieni ***@***.***>; Author ***@***.***>
Betreff: Re: [Jonathan-Gander/LineChartView] Array of strings as label for data (Issue #13)


Aaah! OK, I got it!

I will have a look.

**Comment by Jonathan-Gander** [comment]
Can you explain or provide me a use case for this? Why would you display values in chart but display other values (as strings) in labels? I understand technically what you need but not why you need it.

**Comment by claudiocantieni** [comment]
I have an app which calculates the shape state for athletes. The value range for that output is between 0 and 1. 0…0.25 would be very low, 0.25…0.5 low, 0.5…0.75 normal, 0.75…1 high. I‘d like to represent the history of the shape state in a graph with these four texts seen. I would code the order. Example: [0.3, 0.5, 0.1, 0.9] represented with -> [”low”, ”medium“, ”very low“, ”high“].

________________________________
Von: Jonathan Gander ***@***.***>
Gesendet: Montag, Mai 30, 2022 8:28 AM
An: Jonathan-Gander/LineChartView ***@***.***>
Cc: Claudio Cantieni ***@***.***>; Author ***@***.***>
Betreff: Re: [Jonathan-Gander/LineChartView] Array of strings as label for data (Issue #13)


Can you explain or provide me an example of a use case for this? Why would you display values in chart but display other values (as strings)? I understand technically what you need but not why you need it.

**Comment by Jonathan-Gander** [comment]
And I assume you don't want something like this?

![Simulator Screen Shot - iPhone 12 - 2022-05-30 at 16 47 49](https://user-images.githubusercontent.com/1695222/171016729-82e20ebe-7cf6-4102-845c-6398c17011fc.png)

You only want the `Low` instead of `0.4`, right?

Other question: What if I add a parameter to replace Value label with String Label ? Instead of displaying value and label, it would only display the label.

**Comment by claudiocantieni** [comment]
Yes, without the 0.4 would be ideal.
________________________________
Von: Jonathan Gander ***@***.***>
Gesendet: Monday, May 30, 2022 4:49:17 PM
An: Jonathan-Gander/LineChartView ***@***.***>
Cc: Claudio Cantieni ***@***.***>; Author ***@***.***>
Betreff: Re: [Jonathan-Gander/LineChartView] Array of strings as label for data (Issue #13)


And I assume you don't want to have something like this?

[Simulator Screen Shot - iPhone 12 - 2022-05-30 at 16 47 49]<https://user-images.githubusercontent.com/1695222/171016729-82e20ebe-7cf6-4102-845c-6398c17011fc.png>

You only want the Low instead of 0.4, right?

**Comment by Jonathan-Gander** [comment]
OK.

I've made changes in parameters to simplify your feature. I will try to have a look this week to find a (nice) solution!

See #14 and `v1.3.0` for more details.

**Comment by claudiocantieni** [comment]
Thank you!
________________________________
Von: Jonathan Gander ***@***.***>
Gesendet: Monday, May 30, 2022 6:53:47 PM
An: Jonathan-Gander/LineChartView ***@***.***>
Cc: Claudio Cantieni ***@***.***>; Author ***@***.***>
Betreff: Re: [Jonathan-Gander/LineChartView] Array of strings as label for data (Issue #13)


OK.

I've made changes in parameters to simplify your feature. I will try to have a look this week to find a (nice) solution!

**Comment by Jonathan-Gander** [comment]
Hey @claudiocantieni feature is now ready and commited. Check the brand new `v1.4.0`.

To do what you want, you can simply add this parameter to your `LineChartParameters`: 

```swift
displayMode: .noValues
```

(Add it right after `dotsWidth` parameter. You can also check updated README.)

I hope you like this feature. Let me know!

**Comment by claudiocantieni** [comment]
It works for me! Thank you very much for your work.

________________________________
Von: Jonathan Gander ***@***.***>
Gesendet: Friday, June 3, 2022 5:42:17 PM
An: Jonathan-Gander/LineChartView ***@***.***>
Cc: Claudio Cantieni ***@***.***>; Mention ***@***.***>
Betreff: Re: [Jonathan-Gander/LineChartView] Array of strings as label for data (Issue #13)


Hey @claudiocantieni<https://github.com/claudiocantieni> feature is now ready and commited. Check the brand new v1.4.0.

To do what you want, you can simply add this parameter to your LineChartParameters:

displayMode: .noValues

(Add it right after dotsWidth parameter. You can also check updated README.)

I hope you like this feature. Let me know!
