### ISSUE TITLE
Option to specify precision or use [Int]

### ISSUE THREAD

**Issue by jojost1** [Jonathan-Gander/LineChartView#5]
Hi,

I love this library you built!

I thought it might be nice to be able to have an option to round numbers to for example 0 decimal points, as I kind of want to use this for `[Int]`. When I convert to Double, the chart will always display `XXX.00`.

Cheers!

**Comment by Jonathan-Gander** [comment]
Great idea! I will have a look.

**Comment by Jonathan-Gander** [comment]
@jojost1 It is ready. You can update to `1.1.0` version.

Simply set `dataPrecisionLength` to `0` (in your case) to change precision. Note that it only works on iOS 15 and more. On iOS 14, it stays with two digits.

**Comment by jojost1** [comment]
Works great! Thanks 😄
